### ISSUE TITLE
[1] Main screen - Lấy sai value CH4

### ISSUE THREAD

**Issue by trangkieu2310** [KSP-IMSAT/KSP3_Application#2]
![image](https://user-images.githubusercontent.com/129745728/230701804-c116914d-2178-4670-aad9-ddc57c95f854.png)
![image](https://user-images.githubusercontent.com/129745728/230701826-1734bc34-9ecb-4340-8db9-2b79d48bde05.png)

**Comment by TiepHoangDev** [comment]
fixed
