### ISSUE TITLE
Lỗi đóng ứng dụng trên thanh taskbar

### ISSUE THREAD

**Issue by trangkieu2310** [KSP-IMSAT/KSP3_Application#3]
Click lần 1 vào biểu tượng trên thanh taskbar : mở ứng dụng
Click lần 2 vào biểu tượng trên thanh taskbar : đóng ứng dụng
Hiện tại click lần 2 không đóng được ứng dụng
![image](https://user-images.githubusercontent.com/129745728/230704760-c535ad0b-a6e3-4efc-94af-5740ab86c15c.png)

**Comment by TiepHoangDev** [comment]
fixed
